# Alacritty Colors Configuration
# Catppuccin Mocha theme

[colors]
primary = { background = "#1e1e2e", foreground = "#cdd6f4" }
cursor = { text = "#1e1e2e", cursor = "#f5e0dc" }
vi_mode_cursor = { text = "#1e1e2e", cursor = "#b4befe" }
selection = { text = "#1e1e2e", background = "#f5e0dc" }
search = { matches = { foreground = "#1e1e2e", background = "#a6adc8" }, focused_match = { foreground = "#1e1e2e", background = "#a6e3a1" } }
hints = { start = { foreground = "#1e1e2e", background = "#f9e2af" }, end = { foreground = "#1e1e2e", background = "#a6adc8" } }
line_indicator = { foreground = "None", background = "None" }
footer_bar = { foreground = "#1e1e2e", background = "#a6adc8" }

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc" 